language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: pages # Specifies we’re using GitHub Pages.
  skip-cleanup: true # Tells Travis not to delete build files.
  github-token: "$github_token"  # Enter github_token (variable) & the token in TravisCi. Using an environment variable to avoid exposing our token to the public.
  keep-history: true
  local_dir: build # Tells Travis to only take the files from the /build directory for deployment.
  on:
    branch: master # Tells Travis when to trigger deployment. We only want to deploy when we push to the master branch of the repository.